version: '2.1'

services:
  db:
    image: sha256:e391d6bf9e6d7b9b12bfb2535a390f63bbce9f4a40f34fc07d2c2467b25111f9
    command: "-c log_statement=all"
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "psql -U postgres -c \"SELECT 1 FROM pg_database WHERE datname = 'postgres';\" | grep -q 1" ]
      interval: 1000s
      timeout: 10s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres